// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/zlllgp/vegas/internal/application/app"
	"github.com/zlllgp/vegas/internal/domain/service"
	"github.com/zlllgp/vegas/internal/infrastructure/persistence"
	"github.com/zlllgp/vegas/internal/infrastructure/rpc"
)

// Injectors from wire_gen.go:

func InitVegasApp() *app.VegasServiceImpl {
	rmbRepository := rpc.NewRmbRepository()
	activityRepository := persistence.NewActivityRepository()
	drawService := service.NewDrawService(rmbRepository, activityRepository)
	vegasServiceImpl := app.NewVegasServiceImpl(drawService)
	return vegasServiceImpl
}

func InitRightApp() *app.RightServiceImpl {
	rightRepository := persistence.NewRightRepository()
	rightService := service.NewRightService(rightRepository)
	rightServiceImpl := app.NewRightServiceImpl(rightService)
	return rightServiceImpl
}
