// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/zlllgp/vegas/internal/application/app"
	"github.com/zlllgp/vegas/internal/domain/service"
	"github.com/zlllgp/vegas/internal/infrastructure/cache"
	"github.com/zlllgp/vegas/internal/infrastructure/persistence"
	"github.com/zlllgp/vegas/internal/infrastructure/redis"
	"github.com/zlllgp/vegas/internal/infrastructure/rpc"
)

// Injectors from wire_gen.go:

func InitVegasApp() *app.VegasServiceImpl {
	rmbRepository := rpc.NewRmbRepository()
	activityRepository := persistence.NewActivityRepository()
	redisActivity := redis.NewRedisActivity()
	gCache := cache.NewGCache()
	activityServiceImpl := service.NewActivityServiceImpl(activityRepository, redisActivity, gCache)
	drawServiceImpl := service.NewDrawServiceImpl(rmbRepository, activityServiceImpl)
	vegasServiceImpl := app.NewVegasServiceImpl(drawServiceImpl)
	return vegasServiceImpl
}

// wire_gen.go:

func InitRightApp() *app.RightServiceImpl {
	rightRepository := persistence.NewRightRepository()
	rightService := service.NewRightServiceImpl(rightRepository)
	rightServiceImpl := app.NewRightServiceImpl(rightService)
	return rightServiceImpl
}
