// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/zlllgp/vegas/internal/application/app"
	"github.com/zlllgp/vegas/internal/domain/repository"
	"github.com/zlllgp/vegas/internal/domain/service"
	"github.com/zlllgp/vegas/internal/infrastructure/persistence"
	"github.com/zlllgp/vegas/internal/infrastructure/rpc"
)

// Injectors from wire_gen.go:

func InitializeVegasImplService() (*app.VegasServiceImpl, error) {
	rmbRepository := NewRmbRepo()
	activityRepository := NewActivityRepo()
	drawService := NewDrawService(rmbRepository, activityRepository)
	vegasServiceImpl := NewVegasServiceImpl(drawService)
	return vegasServiceImpl, nil
}

// wire_gen.go:

func NewActivityRepo() repository.ActivityRepository {
	return persistence.NewActivityRepository()
}

func NewRmbRepo() repository.RmbRepository {
	return rpc.NewRmbRepository()
}

func NewDrawService(rmbRep repository.RmbRepository, actRep repository.ActivityRepository) *service.DrawService {
	return service.NewDrawService(rmbRep, actRep)
}

func NewVegasServiceImpl(drawService *service.DrawService) *app.VegasServiceImpl {
	return app.NewVegasServiceImpl(drawService)
}

var ProviderSet = wire.NewSet(
	NewActivityRepo,
	NewRmbRepo,
	NewDrawService,
	NewVegasServiceImpl,
)
