// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRuleMetum = "rule_meta"

// RuleMetum mapped from table <rule_meta>
type RuleMetum struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatorID   int64          `gorm:"column:creator_id;not null" json:"creator_id"`
	CreatorName string         `gorm:"column:creator_name;not null" json:"creator_name"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description;not null" json:"description"`
}

// TableName RuleMetum's table name
func (*RuleMetum) TableName() string {
	return TableNameRuleMetum
}
