// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameActivity = "activity"

// Activity mapped from table <activity>
type Activity struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatorID   int64          `gorm:"column:creator_id;not null" json:"creator_id"`
	CreatorName string         `gorm:"column:creator_name;not null" json:"creator_name"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	TenantID    int32          `gorm:"column:tenant_id;not null" json:"tenant_id"`
	IsDel       int32          `gorm:"column:is_del;not null" json:"is_del"`
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
