// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: api/errno.proto

package api

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Err int32

const (
	Err_Success                Err = 0
	Err_ParamErr               Err = 1000
	Err_ActivityNotFoundRrr    Err = 1001
	Err_CSRFErr                Err = 1002
	Err_RegisterErr            Err = 1003
	Err_LoginErr               Err = 1004
	Err_AuthorizationFailedErr Err = 1005
	Err_DataBaseErr            Err = 1006
	Err_DrawErr                Err = 1007
)

// Enum value maps for Err.
var (
	Err_name = map[int32]string{
		0:    "Success",
		1000: "ParamErr",
		1001: "ActivityNotFoundRrr",
		1002: "CSRFErr",
		1003: "RegisterErr",
		1004: "LoginErr",
		1005: "AuthorizationFailedErr",
		1006: "DataBaseErr",
		1007: "DrawErr",
	}
	Err_value = map[string]int32{
		"Success":                0,
		"ParamErr":               1000,
		"ActivityNotFoundRrr":    1001,
		"CSRFErr":                1002,
		"RegisterErr":            1003,
		"LoginErr":               1004,
		"AuthorizationFailedErr": 1005,
		"DataBaseErr":            1006,
		"DrawErr":                1007,
	}
)

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}

func (x Err) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Err) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errno_proto_enumTypes[0].Descriptor()
}

func (Err) Type() protoreflect.EnumType {
	return &file_api_errno_proto_enumTypes[0]
}

func (x Err) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Err.Descriptor instead.
func (Err) EnumDescriptor() ([]byte, []int) {
	return file_api_errno_proto_rawDescGZIP(), []int{0}
}

var File_api_errno_proto protoreflect.FileDescriptor

var file_api_errno_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x2a, 0xa7, 0x01, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x08, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x10, 0xe8, 0x07, 0x12, 0x18, 0x0a, 0x13, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x72,
	0x72, 0x10, 0xe9, 0x07, 0x12, 0x0c, 0x0a, 0x07, 0x43, 0x53, 0x52, 0x46, 0x45, 0x72, 0x72, 0x10,
	0xea, 0x07, 0x12, 0x10, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x45, 0x72,
	0x72, 0x10, 0xeb, 0x07, 0x12, 0x0d, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x72, 0x72,
	0x10, 0xec, 0x07, 0x12, 0x1b, 0x0a, 0x16, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x45, 0x72, 0x72, 0x10, 0xed, 0x07,
	0x12, 0x10, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x61, 0x73, 0x65, 0x45, 0x72, 0x72, 0x10,
	0xee, 0x07, 0x12, 0x0c, 0x0a, 0x07, 0x44, 0x72, 0x61, 0x77, 0x45, 0x72, 0x72, 0x10, 0xef, 0x07,
	0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a,
	0x6c, 0x6c, 0x6c, 0x67, 0x70, 0x2f, 0x76, 0x65, 0x67, 0x61, 0x73, 0x2f, 0x6b, 0x69, 0x74, 0x65,
	0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_errno_proto_rawDescOnce sync.Once
	file_api_errno_proto_rawDescData = file_api_errno_proto_rawDesc
)

func file_api_errno_proto_rawDescGZIP() []byte {
	file_api_errno_proto_rawDescOnce.Do(func() {
		file_api_errno_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_errno_proto_rawDescData)
	})
	return file_api_errno_proto_rawDescData
}

var file_api_errno_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errno_proto_goTypes = []interface{}{
	(Err)(0), // 0: api.Err
}
var file_api_errno_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_errno_proto_init() }
func file_api_errno_proto_init() {
	if File_api_errno_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_errno_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errno_proto_goTypes,
		DependencyIndexes: file_api_errno_proto_depIdxs,
		EnumInfos:         file_api_errno_proto_enumTypes,
	}.Build()
	File_api_errno_proto = out.File
	file_api_errno_proto_rawDesc = nil
	file_api_errno_proto_goTypes = nil
	file_api_errno_proto_depIdxs = nil
}

var _ context.Context
