// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *RightRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RightRequest[number], err)
}

func (x *RightRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v User
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.User = &v
	return offset, nil
}

func (x *RightRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Eh, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *RightResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_RightResponse[number], err)
}

func (x *RightResponse) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v Right
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Rights = append(x.Rights, &v)
	return offset, nil
}

func (x *RightRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *RightRequest) fastWriteField1(buf []byte) (offset int) {
	if x.User == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetUser())
	return offset
}

func (x *RightRequest) fastWriteField2(buf []byte) (offset int) {
	if x.Eh == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetEh())
	return offset
}

func (x *RightResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *RightResponse) fastWriteField3(buf []byte) (offset int) {
	if x.Rights == nil {
		return offset
	}
	for i := range x.GetRights() {
		offset += fastpb.WriteMessage(buf[offset:], 3, x.GetRights()[i])
	}
	return offset
}

func (x *RightRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *RightRequest) sizeField1() (n int) {
	if x.User == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetUser())
	return n
}

func (x *RightRequest) sizeField2() (n int) {
	if x.Eh == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetEh())
	return n
}

func (x *RightResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField3()
	return n
}

func (x *RightResponse) sizeField3() (n int) {
	if x.Rights == nil {
		return n
	}
	for i := range x.GetRights() {
		n += fastpb.SizeMessage(3, x.GetRights()[i])
	}
	return n
}

var fieldIDToName_RightRequest = map[int32]string{
	1: "User",
	2: "Eh",
}

var fieldIDToName_RightResponse = map[int32]string{
	3: "Rights",
}
