// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRight = "user_right"

// UserRight mapped from table <user_right>
type UserRight struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID           int64          `gorm:"column:user_id;not null" json:"user_id"`
	UserName         string         `gorm:"column:user_name;not null" json:"user_name"`
	ActivityID       int64          `gorm:"column:activity_id;not null" json:"activity_id"`
	PlanID           int64          `gorm:"column:plan_id;not null" json:"plan_id"`
	RightsTemplateID int64          `gorm:"column:rights_template_id;not null" json:"rights_template_id"`
	RightsInstanceID int64          `gorm:"column:rights_instance_id;not null" json:"rights_instance_id"`
}

// TableName UserRight's table name
func (*UserRight) TableName() string {
	return TableNameUserRight
}
